name: blowout-progress-server
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Example progress web-server reading values from a blowout-api-server
description: |
   A web server, showing the progress of a blowout-api-server located per default on localhost:9999
   To change default, edit the config.py

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  progress-server:
    command: wrappers/progress-server.sh
    daemon: simple
    plugs: [network, network-bind]
    
parts:
  server:
    plugin: python
    python-version: python3
    source: .
    requirements: ./requirements.txt
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL
      cp -r ./* $SNAPCRAFT_PART_INSTALL/

  wrappers:
    plugin: dump
    source: snap/